#!/bin/sh

HOOKS_DIR="$(dirname "$0")/pre-commit.d"

for hook in "$HOOKS_DIR"/*; do
  bash "$hook"
  RESULT=$?
  if [ $RESULT != 0 ]; then
    echo "$hook returned non-zero: $RESULT, abort commit"
    exit $RESULT
  fi
done

exit 0
