#!/bin/sh

echo "Running ktlint check..."

# Getting current diff
STAGED_PROJECT_FILES=$(git diff --name-only --cached --relative)
# Execute gradle ktlintFormat
OUTPUT=$(./gradlew ktlintFormat)
EXIT_CODE=$?

echo "$STAGED_PROJECT_FILES" | xargs git add || true

if [ $EXIT_CODE -ne 0 ]; then
  echo "$OUTPUT"
  echo "***********************************************"
  echo "             ktlintFormat failed               "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
else
  echo "ktlint completed successfully"
fi
